FROM alpine:latest

LABEL maintainer James Rasell<(jamesrasell@gmail.com)> (@jrasell)
LABEL vendor "jrasell"

ENV SHERPA_VERSION 0.4.0

WORKDIR /usr/bin/

COPY sherpa .

ENTRYPOINT ["sherpa"]

CMD ["--help"]
